Devspot/Controllers/JobPostingsController.cs
using Devspot.Constants;
using Devspot.Models;
using Devspot.Repositories;
using Devspot.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Devspot.Controllers;

[Authorize]
public class JobPostingsController : Controller
{
    private readonly IRepository<JobPosting> _repository;
    private readonly UserManager<IdentityUser> _userManager;

    public JobPostingsController(IRepository<JobPosting> repository, UserManager<IdentityUser> userManager)
    {
        _repository = repository;
        _userManager = userManager;
    }

    // GET
    [AllowAnonymous]
    public async Task<IActionResult> Index()
    {
        if (User.IsInRole(Roles.Employer))
        {
            var allJobPostings = await _repository.GetAllAsync();
            var userId = _userManager.GetUserId(User);
            var filteredJobPostings = allJobPostings.Where(jp => jp.UserId == userId);

            return View(filteredJobPostings);
        }

        var jobPostings = await _repository.GetAllAsync();

        return View(jobPostings);
    }

    [Authorize(Roles = "Admin,Employer")]
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [Authorize(Roles = "Admin,Employer")]
    public async Task<IActionResult> Create(JobPostingViewModel jobPostingVm)
    {
        if (ModelState.IsValid)
        {
            var jobPosting = new JobPosting
            {
                Title = jobPostingVm.Title,
                Description = jobPostingVm.Description,
                Company = jobPostingVm.Company,
                Location = jobPostingVm.Location,
                UserId = _userManager.GetUserId(User)
            };
            await _repository.AddAsync(jobPosting);
            return RedirectToAction(nameof(Index));
        }

        return View(jobPostingVm);
    }

    [HttpDelete]
    [Authorize(Roles = "Admin,Employer")]
    public async Task<IActionResult> Delete(int id)
    {
        var jobPosting = await _repository.GetByIdAsync(id);

        if (jobPosting == null)
        {
            NotFound("Job posting is not found.");
        }

        var userId = _userManager.GetUserId(User);

        if (User.IsInRole(Roles.Admin) == false && jobPosting.UserId != userId)
        {
            return Forbid();
        }

        await _repository.DeleteAsync(id);

        return Ok();
    }
}

Devspot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Devspot</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Devspot.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="JobPostings" asp-action="Index">Devspot</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="JobPostings" asp-action="Index">All
                            jobs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="JobPostings" asp-action="Create">Create
                            job</a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                        <li>
                            <a class="nav-link" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2025 - Devspot
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>